# Generated by Django 3.0.2 on 2020-04-23 06:06

from django.db import migrations, models
import django_mysql.models
import viewer.utils.filename


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to=viewer.utils.filename.default)),
                ('seg_gt_image', models.ImageField(null=True, upload_to=viewer.utils.filename.default)),
                ('token', models.AutoField(primary_key=True, serialize=False)),
                ('segmentation_area', models.IntegerField(default=0)),
                ('severity_threshold', models.IntegerField(default=0)),
                ('results', django_mysql.models.JSONField(default=dict, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
