# Generated by Django 3.0.2 on 2020-04-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_image', models.ImageField(null=True, upload_to='')),
                ('seg_image_th', models.ImageField(null=True, upload_to='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seg_result', to='viewer.ImageModel')),
            ],
        ),
    ]
