# Generated by Django 3.0.2 on 2020-04-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_imagemodel_results'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SegResultModel',
        ),
    ]
