# Generated by Django 3.0.2 on 2020-04-28 00:46

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_imagemodel_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='segresultmodel',
            name='seg_area',
            field=django_mysql.models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='segresultmodel',
            name='seg_mask',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
