# Generated by Django 3.0.2 on 2020-04-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_auto_20200428_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SegResultModel',
        ),
    ]
