# Generated by Django 3.0.2 on 2020-04-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_delete_segresultmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='segmentation_area',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='severity_threshold',
            field=models.FloatField(default=0.1),
        ),
    ]
