# Generated by Django 3.0.6 on 2020-05-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_auto_20200429_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='severity_threshold',
            field=models.FloatField(default=0.5),
        ),
    ]
