# Generated by Django 3.0.6 on 2020-05-27 05:49

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_auto_20200522_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='seg_gt_image',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='results_hed',
            field=django_mysql.models.JSONField(default=dict, null=True),
        ),
    ]
