version: '2.3'

services:
  segmentation:
    command : /bin/bash
    image: seg_web:0.1
    runtime: nvidia
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - /home/ubuntu/test/segmentation_web:/home/workspace/segmentation
    stdin_open: true
    tty: true

  mysql:
    command : mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    image: mysqldb:0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : "muhan"
      MYSQL_DATABASE : "seg_db"
      MYSQL_USER : "test"
      MYSQL_PASSWORD : "muhanit"
    expose:
      - "3306"
